export  const responseData = {
  success: true,
  message: "Movies retrieved successfully",
  data: [
    {
      id: "6915fe27335151189d9cc957",
      title: "The Matrix",
      year: 1999,
      genre: ["Action", "Sci-Fi"],
      director: "Lana Wachowski",
      actors: ["Keanu Reeves", "Laurence Fishburne"],
      runtime: 136,
      rating: 8.7,
      plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      screenwriter: "Aaron Sorkin",
      studio: "Universal Pictures",
      box_office: "$72896261",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc958",
      title: "The Godfather",
      year: 1972,
      genre: ["Crime", "Drama"],
      director: "Francis Ford Coppola",
      actors: ["Marlon Brando", "Al Pacino"],
      runtime: 175,
      rating: 9.2,
      plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      screenwriter: "Charlie Kaufman",
      studio: "20th Century Fox",
      box_office: "$82356773",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc959",
      title: "Pulp Fiction",
      year: 1994,
      genre: ["Crime", "Drama"],
      director: "Quentin Tarantino",
      actors: ["John Travolta", "Samuel L. Jackson"],
      runtime: 154,
      rating: 8.9,
      plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      screenwriter: "Quentin Tarantino",
      studio: "20th Century Fox",
      box_office: "$16065085",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95a",
      title: "The Dark Knight",
      year: 2008,
      genre: ["Action", "Crime", "Drama"],
      director: "Christopher Nolan",
      actors: ["Christian Bale", "Heath Ledger"],
      runtime: 152,
      rating: 9,
      plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      screenwriter: "Christopher Nolan",
      studio: "20th Century Fox",
      box_office: "$67496057",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95b",
      title: "Forrest Gump",
      year: 1994,
      genre: ["Drama", "Romance"],
      director: "Robert Zemeckis",
      actors: ["Tom Hanks", "Robin Wright"],
      runtime: 142,
      rating: 8.8,
      plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
      screenwriter: "Aaron Sorkin",
      studio: "Paramount",
      box_office: "$31417916",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95c",
      title: "Inception",
      year: 2010,
      genre: ["Action", "Sci-Fi", "Thriller"],
      director: "Christopher Nolan",
      actors: ["Leonardo DiCaprio", "Marion Cotillard"],
      runtime: 148,
      rating: 8.8,
      plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      screenwriter: "Christopher Nolan",
      studio: "MGM",
      box_office: "$3751016",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95d",
      title: "The Shawshank Redemption",
      year: 1994,
      genre: ["Drama"],
      director: "Frank Darabont",
      actors: ["Tim Robbins", "Morgan Freeman"],
      runtime: 142,
      rating: 9.3,
      plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      screenwriter: "Christopher Nolan",
      studio: "Paramount",
      box_office: "$54620942",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95e",
      title: "Schindler's List",
      year: 1993,
      genre: ["Biography", "Drama", "History"],
      director: "Steven Spielberg",
      actors: ["Liam Neeson", "Ben Kingsley"],
      runtime: 195,
      rating: 8.9,
      plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      screenwriter: "Quentin Tarantino",
      studio: "Warner Bros",
      box_office: "$80963440",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc95f",
      title: "Fight Club",
      year: 1999,
      genre: ["Drama"],
      director: "David Fincher",
      actors: ["Brad Pitt", "Edward Norton"],
      runtime: 139,
      rating: 8.8,
      plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
      screenwriter: "Christopher Nolan",
      studio: "Columbia Pictures",
      box_office: "$67570690",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
    {
      id: "6915fe27335151189d9cc960",
      title: "Goodfellas",
      year: 1990,
      genre: ["Biography", "Crime", "Drama"],
      director: "Martin Scorsese",
      actors: ["Robert De Niro", "Ray Liotta"],
      runtime: 146,
      rating: 8.7,
      plot: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
      screenwriter: "Christopher Nolan",
      studio: "20th Century Fox",
      box_office: "$53793169",
      poster_url:
        "https://cdn.pixabay.com/photo/2022/07/17/19/22/movie-7328179_1280.png",
    },
  ],
  pagination: {
    total: 500,
    limit: 10,
    offset: 0,
    hasNext: true,
    hasPrev: false,
  },
};
